# name: DARK-FUNERAL colors for Alacritty
# url: https://github.com/alacritty/alacritty
# upstream: ${upstream}
# author: Andrea Schiavini (original code by Casey Miller)

# Default colors
[colors.primary]
background = '#000000'
# alternate, darker background = '#111113'
foreground = '#c1c1c1'

#[colors.cursor]
#cursor = '#c1c1c1'
#text = '#000000'

# Normal colors
[colors.normal]
black = '#111113'
red =     '#875f5f'  # muted blood red
green =   '#5f8787'  # your provided green
yellow =  '#87875f'  # antique gold / dull brass
blue =    '#5f5f87'  # cold deep blue
magenta = '#875f87'  # grim purple-pink
cyan = '#fbcb97'
white =   '#c1c1c1'  # your provided white

# Bright colors
[colors.bright]
black = '#111113'
red =     '#875f5f'  # muted blood red
green =   '#5f8787'  # your provided green
yellow =  '#87875f'  # antique gold / dull brass
blue =    '#5f5f87'  # cold deep blue
magenta = '#875f87'  # grim purple-pink
cyan = '#fbcb97'
white =   '#c1c1c1'  # your provided white

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#aaaaaa'

[[colors.indexed_colors]]
index = 17
color = '#5f8787'
